version: "3.8"

services:
    client:
        build: client/.
        ports:
            - "5173:5173"
            - "80:80"
            - "8008:8008"
        networks: 
            - backend 
        env_file: "./env/client.env"
        depends_on:
            - server
        extra_hosts:
            - "host.docker.internal:host-gateway"
    server:
        build: express/.
        networks: 
            - backend 
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - PORT=8001
            - HOST=server # not used
        volumes:
            - /home:/home


volumes:
    home:

networks:
    backend:
